function fish_insulter -a command --description "Command not found insulter"
    set INSULTS 
    set INSULTS[1] "Boooo!"
    set INSULTS[2] "Don't you know anything?"
    set INSULTS[3] "RTFM!"
    set INSULTS[4] "Hahaha, n00b!"
    set INSULTS[5] "Wow! That was impressively wrong!"
    set INSULTS[6] "What are you doing??"
    set INSULTS[7] "Pathetic"
    set INSULTS[8] "The worst one today!"
    set INSULTS[9] "n00b alert!"
    set INSULTS[10] "Your application for reduced salary has been sent!"
    set INSULTS[11] "lol"
    set INSULTS[12] "u suk"
    set INSULTS[13] "lol... plz"
    set INSULTS[14] "plz uninstall"
    set INSULTS[15] "And the Darwin Award goes to.... $USER!"
    set INSULTS[16] "ERROR_INCOMPETENT_USER"
    set INSULTS[17] "Incompetence is also competence"
    set INSULTS[18] "Bad."
    set INSULTS[19] "Fake it till you make it!"
    set INSULTS[20] "What is this...? Amateur hour!?"
    set INSULTS[21] "Come on! You can do it!"
    set INSULTS[22] "Nice try."
    set INSULTS[23] "What if... you type an actual command the next time!"
    set INSULTS[24] "What if I told you... it is possible to type valid commands."
    set INSULTS[25] "Y u no speak computer???"
    set INSULTS[26] "This is not Windows"
    set INSULTS[27] "Perhaps you should leave the command line alone..."
    set INSULTS[28] "Please step away from the keyboard!"
    set INSULTS[29] "error code: 1D10T"
    set INSULTS[30] "ACHTUNG! ALLES TURISTEN UND NONTEKNISCHEN LOOKENPEEPERS! DAS KOMPUTERMASCHINE IST NICHT FÜR DER GEFINGERPOKEN UND MITTENGRABEN! ODERWISE IST EASY TO SCHNAPPEN DER SPRINGENWERK, BLOWENFUSEN UND POPPENCORKEN MIT SPITZENSPARKEN. IST NICHT FÜR GEWERKEN BEI DUMMKOPFEN. DER RUBBERNECKEN SIGHTSEEREN KEEPEN DAS COTTONPICKEN HÄNDER IN DAS POCKETS MUSS. ZO RELAXEN UND WATSCHEN DER BLINKENLICHTEN."
    set INSULTS[31] "Pro tip: type a valid command!"
    set INSULTS[32] "Go outside."
    set INSULTS[33] "This is not a search engine."
    set INSULTS[34] "So, I'm just going to go ahead and run rm -rf / for you."
    set INSULTS[35] "Why are you so stupid?!"
    set INSULTS[36] "Perhaps computers is not for you..."
    set INSULTS[37] "Why are you doing this to me?!"
    set INSULTS[38] "Don't you have anything better to do?!"
    set INSULTS[39] "I am _seriously_ considering 'rm -rf /'-ing myself..."
    set INSULTS[40] "This is why you get to see your children only once a month."
    set INSULTS[41] "This is why nobody likes you."
    set INSULTS[42] "Are you even trying?!"

    set count (count $INSULTS)
    echo -e '\033[0;31m'$INSULTS[(random 1 $count)]
    echo -e "Fish: Unknown command: $command"
    return 127
end
