# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"
  - trigger: "serr"
    replace: "System.err.println(\"$|$\");"
  - trigger: "sout"
    replace: "System.out.println(\"$|$\");"
  - trigger: ":oilu"
    replace: "Oi meu amor pra sempre que eu amo demais"
  - trigger: ":sjson"
    replace: |
            {
              "$|$": "dummy_value",
              "dummy_key": "dummy_value2"
            }
  - trigger: ":cjson"
    replace: |
            {
              "$|$": "dummy_value",
              "dummy_key": "dummy_value2",
              "array_key": [
                {
                  "dummy1": "dummy2",
                  "dummy3": "dummy4"
                }
              ]
            }
  - trigger: ":rcrud"
    replace: |
              @GetMapping("/get")
              public ResponseEntity get() {
                return ResponseEntity.ok(new Object());
              }

              @PostMapping("/post")
              public ResponseEntity post(@RequestBody Object object) {
                return ResponseEntity.created(URI.create("")).body(object);
              }

              @PatchMapping("/{id}")
              public ResponseEntity patch(@PathVariable("id") Long id) {
                return ResponseEntity.ok().body(new Object());
              }

              @DeleteMapping("/{id}")
              public ResponseEntity delete(@PathVariable("id") Long id) {
                return ResponseEntity.ok().body(new Object());
              }
  - trigger: ":entityheader"
    replace: |
              @Entity
              @Table(name = "table_name")
  - trigger: ":entityid"
    replace: |
              @Id
              @GeneratedValue(strategy = GenerationType.IDENTITY)
              private Long id;
  - trigger: ":mh"
    replace: "t.cardoso@hotmail.com.br"
  - trigger: ":mg"
    replace: "thi.carsil@gmail.com"
  - trigger: ":mpg"
    replace: "thiago.cardoso33@gmail.com"
  - trigger: ":mi"
    replace: "thiago.c.cardoso-silva@itau-unibanco.com.br"
  - trigger: ":func"
    replace: "987314572"
  - trigger: ":local"
    replace: "http://localhost:8080"
    
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

backend: Clipboard
