#!/bin/bash

# Script to display Day as Dot
# Closebox73

DATE=$(date +"%a")

if [[ "${DATE}" = *seg* ]]; then
    echo "      "
elif [[ "${DATE}" = *ter* ]]; then
    echo "      "
elif [[ "${DATE}" = *qua* ]]; then
    echo "      "
elif [[ "${DATE}" = *qui* ]]; then
    echo "      "
elif [[ "${DATE}" = *sex* ]]; then
    echo "      "
elif [[ "${DATE}" = *sáb* ]]; then
	echo "      "
elif [[ "${DATE}" = *dom* ]]; then
    echo "      "
else
	echo "There are other day??"
fi

exit
